### ISSUE TITLE
PhantomJS 2 support Function#bind and Element#remove

### ISSUE THREAD

**Issue by ariya** [viruschidai/phatomjs-polyfills#1]
Just to clarify, these methods are supported natively in PhantomJS 2. It would be good if this can be clarified, e.g. in the README.

Also, we (=PhantomJS team) don't recommend PhantomJS 1.x anymore (last updated in spring 2013).

**Comment by viruschidai** [comment]
Thx @ariya, I haveupdated README.md file to make it clear that it is only for PhantomJS1.x
